name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify a custom version'
        required: false
        default: ''
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [dev, latest, '']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine version
        id: vars
        run: |
          if [ "${{ matrix.version }}" != "" ]; then
            echo "VERSION=${{ matrix.version }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(date +%Y).$(date +%-m)" >> $GITHUB_ENV
          fi
          echo "VERSION=${{ env.VERSION }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hacs:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
