name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify a custom version'
        required: false
        default: ''
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version != '' && inputs.version || format('{0}.{1}', now|date('Y'), now|date('%-m')) }}
    strategy:
      matrix:
        version: [latest, stable, dev, "${{ env.VERSION }}"]
        arch: [amd64, arm64, arm/v7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            hasscc/hacs:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
          platforms: linux/${{ matrix.arch }}

      - name: Post build completion
        if: always()
        run: echo "Build for Home Assistant ${{ matrix.version }} (${{ matrix.arch }}) complete!"
